#!/usr/bin/env bash
# Nothing of anyone's own finances may be tracked.
#
# The application already keeps this right by construction: the database, the
# log and the certificate live in ~/.dashboard, an uploaded statement is
# parsed in memory and never written to disk, and .gitignore covers the file
# types anyway. This is the backstop for the case those miss -- a statement
# downloaded into the checkout, a fixture built from a real export, a
# .gitignore rule added after the file it was meant to cover.
#
# Three checks, because a rule only helps against the mistake it describes.

set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

fail=0

# 1. File types that are never test material.
if git ls-files | grep -E '(^|/)\.env$|\.(db|sqlite3?|key|pem|ofx|qfx)$'; then
  echo "BLOCKED — a sensitive file type is tracked"
  fail=1
fi

# 2. A CSV outside the fixture directory, and an oversized one inside it.
#    .gitignore allows tests/fixtures/**/*.csv so parser tests can carry a
#    sample; a real export is far larger than a sample needs to be, and that
#    size difference is the only automatic way to tell them apart.
if git ls-files '*.csv' | grep -v '^tests/fixtures/'; then
  echo "BLOCKED — a CSV outside tests/fixtures is tracked"
  fail=1
fi
while IFS= read -r f; do
  [ -f "$f" ] || continue
  size=$(wc -c < "$f")
  if [ "$size" -gt 4096 ]; then
    echo "BLOCKED — $f is ${size}B; a fixture should be a handful of rows,"
    echo "          and a real statement export is not"
    fail=1
  fi
done < <(git ls-files 'tests/fixtures/*.csv')

# 3. Secrets nobody meant to track. deploy/secrets is generated by
#    bootstrap.sh and holds real values on a configured host.
if git ls-files deploy/secrets | grep -v -x 'deploy/secrets/.gitkeep' | grep .; then
  echo "BLOCKED — a real secret file is tracked"
  fail=1
fi

[ "$fail" -eq 0 ] && echo "clean — no personal or financial data tracked"
exit "$fail"
